import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	
	// ⭐️ 關鍵設定：告訴 esbuild 這些東西不要打包！
	// 這裡使用了萬用字元，徹底排除所有 CodeMirror 相關模組
	external: [
		"obsidian",
		"electron",
		"@codemirror/*",
		"fs",
		"path",
		"url",
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}

